// Initialize the map
mapboxgl.accessToken =
  "pk.eyJ1IjoiZmRkdmlzdWFscyIsImEiOiJjbGZyODY1dncwMWNlM3pvdTNxNjF4dG1rIn0.wX4YYvWhm5W-5t8y5pp95w";
const map = new mapboxgl.Map({
  container: "map",
  style: "mapbox://styles/fddvisuals/clsnduc8o01tx01qrgf7ubzyu",
  // style: "mapbox://styles/mapbox/light-v11",
  zoom: 3.04,
  center: [153.244, 6.439],
});

// Load GeoJSON data
map.on("load", function () {
  map.addSource("data", {
    type: "geojson",
    data: "src/data.geojson",
  });

  map.addLayer({
    id: "eez-boundaries",
    type: "fill",
    source: "data",
    paint: {
      "fill-color": [
        "match",
        ["get", "ISO_SOV1"],
        ["USA"],
        "#03045e",
        [
          "AIA",
          "ATG",
          "BHS",
          "BLZ",
          "BM",
          "CAN",
          "COL",
          "CPV",
          "CUB",
          "DMA",
          "EGY",
          "ETH",
          "GHA",
          "GNB",
          "GRL",
          "GUY",
          "HTI",
          "ITA",
          "KNA",
          "LBN",
          "LCA",
          "LKA",
          "MNE",
          "MRT",
          "MUS",
          "NAM",
          "NZL",
          "PAK",
          "RWA",
          "SGP",
          "SMR",
          "SRB",
          "TGO",
          "TKM",
          "VAT",
          "VNM",
        ],
        "#104b95",
        // ["JPN", "KOR", "PHL", "THA", "AUS"],
        // "#0096c7",
        // ["TWN"],
        // "rgba(11, 213, 42, 0.69)",
        // ["TLS", "PNG", "SLB", "VUT", "FJI", "TON", "WSM", "KIR"],
        // "#eb0000",
        [
          "ABW",
          "AFG",
          "AGO",
          "ALB",
          "ARE",
          "ARG",
          "ARM",
          "AUS",
          "AUT",
          "AZE",
          "BDI",
          "BEL",
          "BEN",
          "BFA",
          "BGD",
          "BGR",
          "BHR",
          "BIH",
          "BLR",
          "BOL",
          "BRA",
          "BRB",
          "BRN",
          "BTN",
          "BWA",
          "CAF",
          "CHE",
          "CHL",
          "CIV",
          "CMR",
          "COD",
          "COG",
          "COM",
          "CRI",
          "CUW",
          "CYP",
          "CZE",
          "DEU",
          "DJI",
          "DNK",
          "DOM",
          "DZA",
          "ECU",
          "ERI",
          "ESP",
          "EST",
          "FIN",
          "FJI",
          "FLK",
          "FRA",
          "FRO",
          "FSM",
          "GAB",
          "GBR",
          "GEO",
          "GIB",
          "GIN",
          "GMB",
          "GNQ",
          "GRC",
          "GTM",
          "HKG",
          "HND",
          "HRV",
          "HUN",
          "IDN",
          "IND",
          "IRL",
          "IRN",
          "IRQ",
          "ISL",
          "ISR",
          "JAM",
          "JOR",
          "JPN",
          "KAZ",
          "KEN",
          "KGZ",
          "KHM",
          "KIR",
          "KOR",
          "KWT",
          "LAO",
          "LBR",
          "LBY",
          "LSO",
          "LTU",
          "LUX",
          "LVA",
          "MAR",
          "MDA",
          "MDG",
          "MDV",
          "MEX",
          "MHL",
          "MKD",
          "MLI",
          "MLT",
          "MMR",
          "MNG",
          "MOZ",
          "MSR",
          "MW",
          "MYS",
          "NCL",
          "NER",
          "NGA",
          "NIC",
          "NLD",
          "NOR",
          "NR",
          "OMN",
          "PAN",
          "PER",
          "PHL",
          "PLW",
          "PNG",
          "POL",
          "PRK",
          "PRT",
          "PRY",
          "PSE",
          "PYF",
          "QAT",
          "ROU",
          "RUS",
          "SAU",
          "SDN",
          "SEN",
          "SLB",
          "SLE",
          "SLV",
          "SOM",
          "SSD",
          "STP",
          "SUR",
          "SVK",
          "SVN",
          "SWE",
          "SWZ",
          "SXM",
          "SYC",
          "SYR",
          "TCD",
          "TH",
          "TJK",
          "TLS",
          "TON",
          "TTO",
          "TUN",
          "TUR",
          "TUV",
          "TWN",
          "TZA",
          "UGA",
          "UKR",
          "URY",
          "UZB",
          "VCT",
          "VEN",
          "VUT",
          "WSM",
          "YEM",
          "ZAF",
          "ZMB",
        ],
        "#eb0000",
        "rgba(96, 92, 92, 0.5)",
      ],
      "fill-opacity": 0.7,
      "fill-outline-color": "#FFFFFF",
    },
  });

  map.addLayer({
    id: "eez-text",
    type: "symbol",
    source: "data",
    layout: {
      "text-field": ["get", "GEONAME"],
      "text-font": ["Open Sans Bold", "Arial Unicode MS Bold"],
      "text-size": 12,
      "text-allow-overlap": false,
      "symbol-placement": "point",
      "symbol-spacing": 1000000,
    },
    paint: {
      "text-color": "#FFFFFF",
    },
  });

  updateMap();
});

// Toggleable Filters
const filterGroup = document.getElementById("filter-group");

let categories = [
  {
    name: "USA > China",
    countries: [
      "AIA",
      "ATG",
      "BHS",
      "BLZ",
      "BM",
      "CAN",
      "COL",
      "CPV",
      "CUB",
      "DMA",
      "EGY",
      "ETH",
      "GHA",
      "GNB",
      "GRL",
      "GUY",
      "HTI",
      "ITA",
      "KNA",
      "LBN",
      "LCA",
      "LKA",
      "MNE",
      "MRT",
      "MUS",
      "NAM",
      "NZL",
      "PAK",
      "RWA",
      "SGP",
      "SMR",
      "SRB",
      "TGO",
      "TKM",
      "VAT",
      "VNM",
    ],
    color: "#03045e",
  },
  {
    name: "China > USA",
    countries: [
      "ABW",
      "AFG",
      "AGO",
      "ALB",
      "ARE",
      "ARG",
      "ARM",
      "AUS",
      "AUT",
      "AZE",
      "BDI",
      "BEL",
      "BEN",
      "BFA",
      "BGD",
      "BGR",
      "BHR",
      "BIH",
      "BLR",
      "BOL",
      "BRA",
      "BRB",
      "BRN",
      "BTN",
      "BWA",
      "CAF",
      "CHE",
      "CHL",
      "CIV",
      "CMR",
      "COD",
      "COG",
      "COM",
      "CRI",
      "CUW",
      "CYP",
      "CZE",
      "DEU",
      "DJI",
      "DNK",
      "DOM",
      "DZA",
      "ECU",
      "ERI",
      "ESP",
      "EST",
      "FIN",
      "FJI",
      "FLK",
      "FRA",
      "FRO",
      "FSM",
      "GAB",
      "GBR",
      "GEO",
      "GIB",
      "GIN",
      "GMB",
      "GNQ",
      "GRC",
      "GTM",
      "HKG",
      "HND",
      "HRV",
      "HUN",
      "IDN",
      "IND",
      "IRL",
      "IRN",
      "IRQ",
      "ISL",
      "ISR",
      "JAM",
      "JOR",
      "JPN",
      "KAZ",
      "KEN",
      "KGZ",
      "KHM",
      "KIR",
      "KOR",
      "KWT",
      "LAO",
      "LBR",
      "LBY",
      "LSO",
      "LTU",
      "LUX",
      "LVA",
      "MAR",
      "MDA",
      "MDG",
      "MDV",
      "MEX",
      "MHL",
      "MKD",
      "MLI",
      "MLT",
      "MMR",
      "MNG",
      "MOZ",
      "MSR",
      "MW",
      "MYS",
      "NCL",
      "NER",
      "NGA",
      "NIC",
      "NLD",
      "NOR",
      "NR",
      "OMN",
      "PAN",
      "PER",
      "PHL",
      "PLW",
      "PNG",
      "POL",
      "PRK",
      "PRT",
      "PRY",
      "PSE",
      "PYF",
      "QAT",
      "ROU",
      "RUS",
      "SAU",
      "SDN",
      "SEN",
      "SLB",
      "SLE",
      "SLV",
      "SOM",
      "SSD",
      "STP",
      "SUR",
      "SVK",
      "SVN",
      "SWE",
      "SWZ",
      "SXM",
      "SYC",
      "SYR",
      "TCD",
      "TH",
      "TJK",
      "TLS",
      "TON",
      "TTO",
      "TUN",
      "TUR",
      "TUV",
      "TWN",
      "TZA",
      "UGA",
      "UKR",
      "URY",
      "UZB",
      "VCT",
      "VEN",
      "VUT",
      "WSM",
      "YEM",
      "ZAF",
      "ZMB",
    ],
    color: "#eb0000",
  },
];


//hover color

categories.forEach((category) => {
  let input = document.createElement("input");
  input.type = "checkbox";
  input.id = category.name;
  input.checked = true;

  input.addEventListener("change", function () {
    updateMap();
  });

  let label = document.createElement("label");
  label.setAttribute("for", category.name);
  label.textContent = category.name;

  filterGroup.appendChild(input);
  filterGroup.appendChild(label);
});

function updateMap() {
  let checkedCountriesColors = [];

  categories.forEach((category) => {
    let checkbox = document.getElementById(category.name);
    if (checkbox.checked) {
      category.countries.forEach(country => {
        checkedCountriesColors.push(country, category.color);
      });
    }
  });

  // Update paint properties  
  map.setPaintProperty('eez-boundaries', 'fill-color', [
    "match",
    ["get", "ISO_SOV1"],
    ...checkedCountriesColors,
    "rgba(96, 92, 92, 0.5)" // Default fill color for unchecked countries
  ]);
}

